version: 2
updates:
  - package-ecosystem: npm
    directory: /docs
    schedule:
      interval: weekly
      day: monday
    groups:
      documentation:
        patterns: ["*"]
    labels: [dependencies]
    commit-message:
      prefix: "build(docs)"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      actions:
        patterns: ["*"]
    labels: [dependencies, ci]
    commit-message:
      prefix: "ci"
  - package-ecosystem: pip
    directory: /.github
    schedule:
      interval: weekly
      day: monday
    labels: [dependencies, ci]
    commit-message:
      prefix: "ci"
