/*===- weavec_chk_report.c - Out-of-line report-mode helpers -----*- C -*-===*\
|*
|* Part of WeaveC, under the Apache License v2.0 with LLVM Exceptions.
|* See LICENSE for license information.
|* SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
|*
|*===----------------------------------------------------------------------===*|
|*
|* RFC 0030, section 10.9: the report family of libweavec_chk.a, generated by
|* `weavec-cc -fweavec-print-prelude=out-of-line -fweavec-checks=report`.
|* One archive cannot define two signatures under one name, so these helpers
|* carry a `_report` suffix (`__weavec_chk_nonnull_report`, ...,
|* `__weavec_strnlen_report`); they call __weavec_rt_report, from
|* libweavec_rt.a.
|*
\*===----------------------------------------------------------------------===*/

#include "weavec_chk_report_helpers.inc"
