/*===- weavec_chk.c - Out-of-line check helpers ------------------*- C -*-===*\
|*
|* Part of WeaveC, under the Apache License v2.0 with LLVM Exceptions.
|* See LICENSE for license information.
|* SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
|*
|*===----------------------------------------------------------------------===*|
|*
|* RFC 0030, section 10.9. Injecting the prelude would change the predefines
|* of a precompiled header built by plain Clang, so with -include-pch,
|* -fmodules or an implicit PCH weavec-cc declares the helpers without bodies
|* and links lib/weavec/libweavec_chk.a, built from this file and
|* weavec_chk_report.c. The definitions are the prelude's own, generated by
|* `weavec-cc -fweavec-print-prelude=out-of-line -fweavec-checks=verify` at
|* build time: the trap and verify families, the term helpers and, where the
|* C library has a usable-size query, the zero-initialisation wrappers. The
|* report family is in weavec_chk_report.c, a separate member, so that only
|* report builds need libweavec_rt.a.
|*
|* The host compiler that builds WeaveC compiles this file; without
|* __builtin_verbose_trap the helpers use __builtin_trap().
|*
\*===----------------------------------------------------------------------===*/

#if defined(__has_builtin)
#if __has_builtin(__builtin_verbose_trap)
#define WEAVEC_CHK_TRAP(category, reason)                                      \
  __builtin_verbose_trap(category, reason)
#endif
#endif
#ifndef WEAVEC_CHK_TRAP
#define WEAVEC_CHK_TRAP(category, reason) __builtin_trap()
#endif

#if defined(__APPLE__)
#include <malloc/malloc.h>
#define WEAVEC_CHK_USABLE(p) malloc_size(p)
#elif defined(__FreeBSD__)
#include <malloc_np.h>
#define WEAVEC_CHK_USABLE(p) malloc_usable_size(p)
#elif defined(__linux__)
#include <malloc.h>
#define WEAVEC_CHK_USABLE(p) malloc_usable_size(p)
#endif

#include "weavec_chk_helpers.inc"
